### ISSUE TITLE
Mac M1 Docker error

### ISSUE THREAD

**Issue by renja-g** [fastapi/full-stack-fastapi-template#707]
On my M1 I get the following error when trying to run `docker-compose.yml` via `docker compose up -d`:
```
 ! backend The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s
```

**Comment by dudil** [comment]
Hi @renja-g, a quick fix would be to add the following line into the docker-compose.yml backend section:
``` yaml
...
...
build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    
    platform: linux/amd64 # Add this line for M1 Macs
...
...
```

@tiangolo , I will issue a PR for quickly fix that if you don't mind.

I'm not sure why the base image you are building from [tiangolo/uvicorn-gunicorn](https://hub.docker.com/r/tiangolo/uvicorn-gunicorn/tags) is marked as supporting only amd64,
The base image of that one is python:3.10 which also supports arm64.
